workflows:
  ios_release:
    name: "iOS Release Build"
    max_build_duration: 60

    integrations:
      app_store_connect: integration

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install Flutter packages
        script: flutter pub get

      - name: Build iOS release (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
