platform :ios, '13.0'

install! 'cocoapods', :deterministic_uuids => false

flutter_root = File.expand_path('..', File.dirname(__FILE__))
require File.expand_path(File.join(flutter_root, '.ios', 'Flutter', 'podhelper.rb'))

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  flutter_additional_ios_build_settings(installer)
end
